PUT http://localhost:3003/api/blogs/5a422a851b54a676234d17f7
Content-Type: application/json

{
    "title": "Updated Blogi", 
    "author": "Updater",
    "url": "http://update.com",
    "likes": 99
}